### ISSUE TITLE
Automate process for updating TLD list from IANA

### ISSUE THREAD

**Issue by rossanthony** [hapijs/tlds#6]
### Runtime

n/a

### Runtime version

n/a

### Module version

n/a

### How can we help?

Would it be possible to setup a scheduled github action (perhaps nightly or even weekly would probably suffice) to run a script to fetch the latest list from https://data.iana.org/TLD/tlds-alpha-by-domain.txt and update the list in this package? It could open a PR if there's a diff for someone to manually review and approve. But the action of doing so should email the contributors so they are notified there's been a change made by IANA which needs to be merged in.

**Comment by Marsup** [comment]
Thanks for the suggestion, it motivated me to tackle that, it shouldn't be a problem anymore.

**Comment by Nargonath** [comment]
Thanks @Marsup
